#Do not change this value
ConfigVersion: "${project.version}"

Settings:
  #Make sure this setting is the same on all servers in your network
  UseAccurateSenderParser: true

  TagEveryIdentifiableMessage: false

  #Handling messages from the Proxy
  HandlingProxyMessage: true

  #A list of private message commands on your server
  #The plugin will attempt to parse placeholder inside these commands.
  #This list is in REGEX, so you can do some more advanced matches.
  CommandsToParse:
    - "(?i)/emsg .*"
    - "(?i)/msg .*"
    - "(?i)/pm .*"
    - "(?i)/tell .*"
    - "(?i)/r .*"

  #You might want to adjust this option if you have other plugins listening to the chat
  #And it is interfering with InteractiveChat's placeholders
  #Valid options are
  #.
  #For bungeecord:
  #LOWEST, LOW, NORMAL, HIGH/DEFAULT, HIGHEST
  #.
  #For Velocity:
  #FIRST, EARLY, NORMAL, LATE/DEFAULT, LAST
  ChatEventPriority: DEFAULT
